#!/usr/bin/env zsh
tmp=

successfully() {
  $* || (echo "failed" 1>&2 && exit 1)
}

function vundle () {
  vim -c "execute \"BundleInstall\" | q | q"
}

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa -b 4096

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  successfully open https://github.com/account/ssh
  vared -p "Press any key once you have pasted into your Github account..." tmp

echo "Upgrade base gem system to latest version"
  successfully sudo gem update --system
  successfully sudo gem clean

echo "Installing Homebrew, a good OS X package manager ..."
  successfully ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"
  successfully brew update

echo "Installing lastest zsh, for shell"
  successfully brew install zsh
  successfully sudo echo "/usr/local/bin/zsh" >> /etc/shells
  successfully chsh -s /usr/local/bin/zsh

echo "Installing Postgres, a good open source relational database ..."
  successfully brew install postgresql --no-python
  successfully initdb /usr/local/var/postgres -E utf8

echo "Installing Redis, a good key-value database ..."
  successfully brew install redis

echo "Installing ack, for searching the contents of files ..."
  successfully brew install ack

echo "Installing fasd, for fast directory navigation..."
  successfully brew install fasd

echo "Installing macvim, for better editing ..."
  successfully brew install macvim

echo "Installing wget, for better file downloading ..."
  successfully brew install wget

echo "Installing git, for better version control ..."
  successfully brew install git
  successfully brew install git-extras
  successfully brew install legit
  successfully legit install

echo "Fetch dotfiles"
  successfully git clone git@github.com:damonmorgan/dotfiles.git ~/.dotfiles

echo "Install dotfiles"
  successfully cd ~/.dotfiles
  successfully git submodule update --init
  successfully rake install

echo "Fetch better programming font"
  successfully wget http://www.levien.com/type/myfonts/Inconsolata.otf
  vared -p "Press any key once you have installed the Inconsolata font..." tmp

echo "Install rbenv (a Ruby version manager)"
  successfully brew install rbenv
  successfully brew install ruby-build
  successfully rbenv init - zsh

echo "Install lastest ruby"
  successfully rbenv install 1.9.3-p374
  successfully rbenv rehash

echo "Installing pow"
  successfully brew install pow

echo "install other development languages"
  successfully brew install node
  successfully brew install python

echo "Installing standalone Heroku CLI client. You'll need administrative rights on your machine ..."
  successfully wget -qO- https://toolbelt.heroku.com/install.sh | sh

echo "Installing heroku plugins"
  successfully /usr/local/heroku/bin/heroku plugins:install git://github.com/ddollar/heroku-config.git
  successfully /usr/local/heroku/bin/heroku plugins:install git://github.com/ddollar/heroku-accounts.git
  successfully /usr/local/heroku/bin/heroku plugins:install git://github.com/heroku/heroku-pg-extras.git

echo "Init Vundle and Install"
  successfully vundle

echo "Building Command-T plugin"
  successfully cd ~/.dotfiles/vim/bundle/command-t
  successfully rake make

echo "Create development directory"
  successfully cd ~/
  successfully mkdir development

echo "Install snippets"
  successfully cd ~/development
  successfully git clone git://github.com/scrooloose/snipmate-snippets.git
  successfully cd ~/development/snipmate-snippets
  vared -p "Press any key once you have edited Rakefile and changed snipmate to snipmate.vim" tmp
  successfully rake deploy_local

echo "Get better colour scheme for terminal"
  successfully cd ~/development
  successfully git clone git://github.com/altercation/solarized.git

echo "Install sshuttle for a faster SSH tunnel"
  successfully cd ~/
  successfully git clone git://github.com/apenwarr/sshuttle.git
