#!/usr/bin/env bash

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh
  read -p "Press any key once you have pasted into your Github account..."

echo "Upgrade base gem system to latest version"
  sudo gem update --system
  sudo gem clean

echo "Installing Homebrew, a good OS X package manager ..."
  /usr/bin/ruby -e "$(/usr/bin/curl -fsSL https://raw.github.com/mxcl/homebrew/master/Library/Contributions/install_homebrew.rb)"
  brew update

echo "Installing Packages (git, bash-completion, macvim, ack, wget)"
  brew install git
  brew install bash-completion
  brew install macvim
  brew install ack
  brew install wget

echo "Fetch dotfiles"
  git clone git@github.com:damonmorgan/dotfiles.git ~/.dotfiles

echo "Install dotfiles"
  cd ~/.dotfiles
  git submodule update --init
  rake install

echo "Fetch better programming font"
  wget http://www.levien.com/type/myfonts/Inconsolata.otf
  read -p "Press any key once you have installed the Inconsolata font..."

echo "Launching MacVim"
  mvim .
  read -p "Press any key once you have run :BundleInstall inside of MacVim..."

echo "Building Command-T plugin"
  cd ~/.dotfiles/vim/bundle/command-t
  rake make

echo "Create development directory"
  cd ~/
  mkdir development
  cd ~/development

echo "Install snippets"
  git clone git://github.com/scrooloose/snipmate-snippets.git
  cd ~/development/snipmate-snippets
  read -p "Press any key once you have edited Rakefile and changed snipmate to snipmate.vim"
  rake deploy_local

echo "Get better colour scheme for terminal"
  git clone git://github.com/altercation/solarized.git

echo "Install Databases (sqlite, mysql)"
  brew install sqlite
  brew install mysql
  read -p "Run the scripts indicated to complete installation of mysql and then press any key to continue..."

echo "Install rbenv (a Ruby version manager)"
  brew install rbenv
  brew install ruby-build
  rbenv init -

echo "Install ruby ree 1.8.7 and ruby 1.9.2"
  rbenv install ree-1.8.7-2011.03
  rbenv install 1.9.2-p290
  rbenv rehash
