#!/usr/bin/env zsh
tmp=

successfully() {
  $* || (echo "failed" 1>&2 && exit 1)
}

function vundle () {
  vim -c "execute \"BundleInstall\" | q | q"
}

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa -b 4096
