#!/usr/bin/env zsh
tmp=

successfully() {
  $* || (echo "failed" 1>&2 && exit 1)
}

function vundle () {
  vim -c "execute \"BundleInstall\" | q | q"
}

echo "Building Command-T plugin"
  successfully cd ~/.dotfiles/vim/bundle/command-t
  successfully rake make

echo "Create development directory"
  successfully cd ~/
  successfully mkdir development

echo "Install snippets"
  successfully cd ~/development
  successfully git clone git://github.com/scrooloose/snipmate-snippets.git
  successfully cd ~/development/snipmate-snippets
  vared -p "Press any key once you have edited Rakefile and changed snipmate to snipmate.vim" tmp
  successfully rake deploy_local

echo "Get better colour scheme for terminal"
  successfully cd ~/development
  successfully git clone git://github.com/altercation/solarized.git

echo "Install sshuttle for a faster SSH tunnel"
  successfully cd ~/
  successfully git clone git://github.com/apenwarr/sshuttle.git
