#!/usr/bin/env zsh
tmp=

successfully() {
  $* || (echo "failed" 1>&2 && exit 1)
}

function vundle () {
  vim -c "execute \"BundleInstall\" | q | q"
}

echo "Installing Postgres, a good open source relational database ..."
  successfully brew install postgresql --no-python
  successfully initdb /usr/local/var/postgres -E utf8

echo "Installing Redis, a good key-value database ..."
  successfully brew install redis

echo "Installing ack, for searching the contents of files ..."
  successfully brew install ack

echo "Installing fasd, for fast directory navigation..."
  successfully brew install fasd

echo "Installing macvim, for better editing ..."
  successfully brew install macvim

echo "Installing wget, for better file downloading ..."
  successfully brew install wget

echo "Fetch better programming font"
  successfully wget http://www.levien.com/type/myfonts/Inconsolata.otf
  vared -p "Press any key once you have installed the Inconsolata font..." tmp

echo "Install lastest ruby"
  successfully brew tap homebrew/dupes
  successfully brew install apple-gcc42
  successfully export CC=gcc
  successfully brew install ruby-build
  successfully rbenv install 1.9.3-p385
  successfully rbenv rehash

echo "install other development languages"
  successfully brew install node
  successfully brew install python

echo "Installing pow"
  successfully brew install pow

echo "Installing standalone Heroku CLI client. You'll need administrative rights on your machine ..."
  successfully wget -qO- https://toolbelt.heroku.com/install.sh | sh

echo "Installing heroku plugins"
  successfully /usr/local/heroku/bin/heroku plugins:install git://github.com/ddollar/heroku-config.git
  successfully /usr/local/heroku/bin/heroku plugins:install git://github.com/ddollar/heroku-accounts.git
  successfully /usr/local/heroku/bin/heroku plugins:install git://github.com/heroku/heroku-pg-extras.git

echo "Init Vundle and Install"
  successfully vundle
